version: '3'

services:
  api:
    build:
      context: .
    ports:
      - 80:80
    volumes:
      - .:/app
    networks:
      - dev

    container_name: api

  database:
    image: mysql
    volumes:
      - database-data:/var/lib/mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_DATABASE: 'codex-api'
    networks:
      - dev

    container_name: mysql

  phpmyadmin:
    image: phpmyadmin
    depends_on:
      - database
    ports:
      - 3306:80
    environment:
      PMA_HOST: database
    networks:
      - dev

    container_name: phpmyadmin

networks:
  dev:

volumes:
  database-data: