version: '3'
services:
  backend:
    image: encodex
    build:
      context: .
    environment:
      PYTHONPATH: /app/src
    volumes:
      - .:/app
    ports:
      - 8000:80
    networks:
      - encodex-network
    container_name: encodex-fastapi

  database:
    image: mysql
    volumes:
      - database-data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: 'encodex'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    networks:
      - encodex-network
    container_name: encodex-mysql

  database-manager:
    image: phpmyadmin
    depends_on:
      - database
    ports:
      - 80:80
    environment:
      PMA_HOST: database
    networks:
      - encodex-network
    container_name: encodex-phpmyadmin

volumes:
  database-data:

networks:
  encodex-network: